
services:
  workspace-backend:
    container_name: workspace-backend
    build: ./backend/
    ports:
      - "${WORKSPACE_BACKEND_PORT}:8000"
    networks:
      - workspace
    
  workspace-frontend:
    container_name: workspace-frontend
    build: ./frontend/
    env_file:
      - .env.local
    ports:
        - "${WORKSPACE_FRONTEND_PORT}:3000"
    networks:
      - workspace

networks:
  workspace:
    driver: bridge
