
services:
  workspace-backend:
    container_name: workspace-backend
    build: ./backend/
    env_file:
      - .env
    ports:
      - "8000:80"
    networks:
      - workspace

  workspace-frontend:
    container_name: workspace-frontend
    build: ./frontend/
    env_file:
      - .env
    ports:
        - "3000:3000"
    networks:
      - workspace

networks:
  workspace:
    driver: bridge
