
services:
  workspace-backend:
    container_name: workspace-backend
    build: ./backend/
    env_file:
      - .env
    ports:
      - "${WORKSPACE_BACKEND_PORT}:80"
    networks:
      - workspace
      - cisbaf_network_apps

  workspace-frontend:
    container_name: workspace-frontend
    build: ./frontend/
    env_file:
      - .env
    ports:
        - "${WORKSPACE_FRONTEND_PORT}:3000"
    networks:
      - workspace

networks:
  workspace:
    driver: bridge
  cisbaf_network_apps:
    external: true
