# Generated by Django 5.1.7 on 2025-03-25 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspace', '0006_remove_workspace_user_workspace_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome do WorkSpace')),
                ('image', models.ImageField(blank=True, null=True, upload_to='workpage/', verbose_name='Imagem')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url Destino')),
                ('type', models.CharField(choices=[('external', 'external'), ('embed', 'embed')], max_length=200)),
                ('workspaces', models.ManyToManyField(to='workspace.workspace')),
            ],
        ),
    ]
