# Generated by Django 5.1.7 on 2025-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workpage',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
    ]
