# Generated by Django 5.1.7 on 2025-03-26 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0002_workpage_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workpage',
            name='description',
        ),
    ]
