# Generated by Django 5.1.7 on 2025-03-25 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_workspace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
