# Generated by Django 5.1.7 on 2025-03-26 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_remove_workspace_user_workspace_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AddField(
            model_name='workspace',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='workspace/', verbose_name='Imagem'),
        ),
    ]
