# Generated by Django 5.1.7 on 2025-03-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0005_remove_workpage_workspaces'),
        ('workspace', '0007_workspace_description_workspace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='workpages',
            field=models.ManyToManyField(to='workpage.workpage'),
        ),
    ]
