# Generated by Django 5.1.7 on 2025-04-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workpage', '0007_alter_workpage_group'),
        ('workspace', '0008_workspace_workpages'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='views',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='workpages',
            field=models.ManyToManyField(blank=True, null=True, to='workpage.workpage'),
        ),
    ]
